#pragma config(Motor,  port2,           frontleft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontright,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backright,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backleft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lift,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           dr4b1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           dr4b2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           dr4b3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          dr4b4,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main () {
	int joy_x;            // will hold the X value of the analog stick (choices below)
	int joy_y;            // will hold the Y value of the analog stick (choices below)
	int slowbutton = vexRT[Btn5U];       // either true or false (pressed or not pressed
	int threshold = 5;   // helps to eliminate extra 'noise' from a joystick that isn't perfectly at (0,0)
	while(1 == 1) {
		joy_x = vexRT[Ch4];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
		joy_y = vexRT[Ch3];   // This is the RIGHT analog stick.  For LEFT, change 'Ch2' to 'Ch3'.

		//////////////////////////////////////////////////////////////////////////////////////////////////////
	if (slowbutton == 0) {
		// Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
		if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y > 0)){
			motor[frontleft]  = (joy_y + joy_x);
			motor[backleft]  = (joy_y + joy_x);
			motor[frontright] = (joy_y - joy_x);
			motor[backright] = (joy_y - joy_x);}
		// Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
		else if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y < 0)){
			motor[frontleft]  = (joy_y - joy_x);
			motor[backleft]  = (joy_y - joy_x);
			motor[frontright]  = (joy_y + joy_x);
			motor[backright] = (joy_y + joy_x);}
		// Turning in place to the right: (abs(X) is above the threshold, abs(Y) is below the threshold)
		else if((abs(joy_x) > threshold) && (abs(joy_y) < threshold)){
			motor[frontleft]  = joy_x;
			motor[backleft] = joy_x;
			motor[frontright] = (-1 * joy_x);
			motor[backright] = (-1 * joy_x);}
		// Turning in place to the right: (abs(Y) is above the threshold, abs(X) is below the threshold)
		else if((abs(joy_x) < threshold) && (abs(joy_y) > threshold)){
			motor[frontleft]  = (-1 * joy_x);
			motor[backleft] = (-1 * joy_x);
			motor[frontright] = joy_x;
			motor[backright] = joy_x;}
		// Standing still: (both abs(X) and abs(Y) are below the threshold)
		else{
			motor[frontleft]  = 0;
			motor[backleft]  = 0;
			motor[backright]  = 0;
			motor[frontright] = 0;}
		// Mobile Goal Lift motor
		motor[lift] = vexRT[Ch2];
		// DR4B motors
		motor[dr4b1] = vexRT[Ch3Xmtr2];
		motor[dr4b2] = vexRT[Ch3Xmtr2];
		motor[dr4b3] = vexRT[Ch3Xmtr2];
		motor[dr4b4] = vexRT[Ch3Xmtr2];}

	//////////////////////////////////////////////////////////////////////////////////////////////////////
	if (slowbutton == 1) {

		// Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
		if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y > 0)){
			motor[frontleft]  = (joy_y + joy_x)/10;
			motor[backleft]  = (joy_y + joy_x)/10;
			motor[frontright] = (joy_y - joy_x)/10;
			motor[backright] = (joy_y - joy_x)/10;}
	}
	// Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
	if ((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y < 0) ){
		motor[frontleft]  = (joy_y - joy_x)/10;
		motor[backleft]  = (joy_y - joy_x)/10;
		motor[frontright]  = (joy_y + joy_x)/10;
		motor[backright] = (joy_y + joy_x)/10;}
	// Turning in place: (abs(X) is above the threshold, abs(Y) is below the threshold)
	else if((abs(joy_x) > threshold) && (abs(joy_y) < threshold)){
		motor[frontleft]  = (joy_x)/10;
		motor[backleft] = (joy_x)/10;
		motor[frontright] = (-1 * joy_x)/10;
		motor[backright] = (-1 * joy_x)/10;}
	// Standing still: (both abs(X) and abs(Y) are below the threshold)
	else{
		motor[frontleft]  = 0;
		motor[backleft]  = 0;
		motor[backright]  = 0;
		motor[frontright] = 0;}
	// Mobile Goal Lift motor
	motor[lift] = (vexRT[Ch2])/2;
	// DR4B motors
	motor[dr4b1] = (vexRT[Ch3Xmtr2])/2;
	motor[dr4b2] = (vexRT[Ch3Xmtr2])/2;
	motor[dr4b3] = (vexRT[Ch3Xmtr2])/2;
	motor[dr4b4] = (vexRT[Ch3Xmtr2])/2;}
}
